ovs: Add port setting options
linkernetworks/go-openvswitch pull request #1
Opened 2018-06-27 08:05 UTC by chenyunchen

`ovs-vsctl --format=json set port bond0 vlan_mode=trunk trunk=1,2,3,4,5`
`ovs-vsctl --format=json get port bond0 tag vlan_mode trunk`
```go
[]          // If the option is not exist, OVS will return "[]\n"
trunk       // If the option is not exist, OVS will return "[]\n"
[1,2,3,4,5] // If the option is not exist, OVS will return "[]\n"
```

Only support the tag, vlan_mode, trunk option at this point.
All fields in PortOptions structs are pointers.
```go
type PortOptions struct {
	Tag      *int
	VLANMode *string
	Trunk    []int
}
...
// Tag will be 0 if we just use init without pointer
err := c.VSwitch.Set.Port(port, PortOptions{
	VLANMode: vlanMode,
	Trunk:    trunk,
})
```

2018-06-27 10:37 UTC, John-Lin approved these changes

2018-06-28 03:15 UTC, hwchiu requested changes

2018-06-28 03:15 UTC, hwchiu commented on .travis.yml
> +  - go get github.com/google/go-cmp/cmp
這是不是跟下面第二行重複?

2018-06-28 03:17 UTC, hwchiu approved these changes

2018-06-28 03:23 UTC, merged